services:
  accessmod-api:
    image: fredmoser/accessmod_api:latest
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3000:3000"
    environment:
      - BIND_PATH=${BIND_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BIND_PATH}/data:/data
  accessmod-api-dev:
    image: fredmoser/accessmod_api:latest
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
    ports:
      - "3030:3030"
    environment:
      - BIND_PATH=${BIND_PATH}
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BIND_PATH}/api:/api
      - ${BIND_PATH}/data:/data
      - ${BIND_PATH}/helpers:/helpers
      - ${BIND_PATH}/01_get_data:/01_get_data
      - ${BIND_PATH}/02_build_merged_landcover:/02_build_merged_landcover
      - ${BIND_PATH}/03_create_start_points:/03_create_start_points
      - ${BIND_PATH}/04_travel_time:/04_travel_time

