services:
  accessmod-api:
    image: fredmoser/accessmod_api:latest
    build:
      context: ../
      dockerfile: ./api/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    ports:
      - "3000:3000"
    volumes:
      - .:/api
      - ../shared:/data
      - ../04_travel_time:/run
  accessmod-api-dev:
    image: fredmoser/accessmod_api:latest
    build:
      context: ../
      dockerfile: ./api/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/api
      - ../shared:/data
      - ../04_travel_time:/run
    environment:
      - NODE_ENV=development
    command: ["tail", "-f", "/dev/null"]


