services:
  traefik:
    image: traefik:v2.3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-volume:/etc/traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=frederic.moser@unige.ch
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      - --log.level=INFO

  accessmod:
    image: fredmoser/accessmod_api:latest
    container_name: accessmod
    restart: unless-stopped
    depends_on:
      - traefik
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - http://localhost:3000/get_list_locations
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 10s
    expose:
      - 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.accessmod.rule: Host(`accessmod.mapx.org`)
      traefik.http.routers.accessmod.entrypoints: websecure
      traefik.http.routers.accessmod.tls: "true"
      traefik.http.routers.accessmod.tls.certresolver: letsencrypt
      traefik.http.services.accessmod.loadbalancer.server.port: "3000"

volumes:
  traefik-volume:
